### ISSUE TITLE
How can I fix this error?   No module named 'cldm.model'

### ISSUE THREAD

**Issue by klossm** [ZHO-ZHO-ZHO/ComfyUI-AnyText#3]
ERROR:root:Traceback (most recent call last):
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-AnyText\AnyTextNodeTest.py", line 30, in run_anytext
    pipe = pipeline('my-anytext-task', model='damo/cv_anytext_text_generation_editing', model_revision='v1.1.1', use_fp16=True, use_translator=False)
  File "L:\stable-diffusion\venv\lib\site-packages\modelscope\pipelines\builder.py", line 137, in pipeline
    register_modelhub_repo(model, cfg.get('allow_remote', False))
  File "L:\stable-diffusion\venv\lib\site-packages\modelscope\utils\plugins.py", line 455, in register_modelhub_repo
    import_module_from_model_dir(model_dir)
  File "L:\stable-diffusion\venv\lib\site-packages\modelscope\utils\plugins.py", line 400, in import_module_from_model_dir
    importlib.import_module(submodule)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 17, in <module>
    from cldm.model import create_model, load_state_dict
ModuleNotFoundError: No module named 'cldm.model'

**Comment by botnang** [comment]
same here....

**Comment by Sundragon1993** [comment]
@klossm @botnang any updates on this issue so far?

**Comment by camoody1** [comment]
It looks like that code is referencing the original project code from its GitHub.
https://github.com/tyxsspa/AnyText/blob/main/cldm/model.py

I don't know if we're supposed to clone this project AND the other project, maybe?
